# Site settings
title: Decanter
email: chiara92ceretti@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://decanter.github.io" # the base hostname & protocol for your site
encoding: UTF-8